# 워크플로우 이름: Label Printer Watcher 릴리스 생성
name: Create Release for Label Printer Watcher

# 실행 조건: 'v'로 시작하는 태그가 푸시되었을 때만 실행
on:
  push:
    tags:
      - 'v*.*.*'

# 권한 설정: GitHub Releases에 파일을 쓰기 위한 권한
permissions:
  contents: write

# 실행할 작업
jobs:
  build-and-release:
    # 실행 환경: Windows 최신 버전
    runs-on: windows-latest

    # 단계별 작업 내용
    steps:
      # 1. 소스 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 파이썬 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. 필요한 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. PyInstaller로 .exe 파일 빌드 (assets 폴더 포함)
      - name: Build executable with PyInstaller
        run: pyinstaller --name "Label_Printer_Watcher" --onefile --add-data "assets;assets" label_printer_watcher.py

      # 5. 빌드된 .exe 파일을 ZIP으로 압축
      - name: Zip the executable
        run: |
          Compress-Archive -Path dist/Label_Printer_Watcher.exe -DestinationPath "Label_Printer_Watcher-${{ github.ref_name }}.zip"
      
      # 6. GitHub 릴리스 생성 및 ZIP 파일 업로드
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: "Label_Printer_Watcher-${{ github.ref_name }}.zip"